version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api-service 
    ports:
    - "3001:3001"
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: api-widget
      MYSQL_USER: api-widget-user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data    
volumes:
  mysql_data:
  cache:  
